### PR TITLE
fix: prewarm after function deploy

### LINKED ISSUE #265: Doesn't warmup when deploying just a function
## Issue

On a normal deploy, warming up is done:

```serverless deploy --stage dev```

```
Serverless: WarmUp: Prewarming up you functions using warmer "default".
Serverless: WarmUp: Warmer "default" successfully prewarmed your functions.
```

but when deploying just a function it isn't:

```serverless deploy --stage dev function -f mainFunc```

## Expected Behavior

when prewarm: true is set, deploying only functions causes warmup

## Details

Can run a GET to `https://AWS_GATEWAY_HOST/dev/main` after just deploying function and check logs to see if it had been warmed up.

serverless.yml:

```
service: issueWithWarmupPlugin

plugins:
  - serverless-plugin-warmup

provider:
  name: aws

functions:
  mainFunc:
    handler: src/index.mainFunc
    events:
      - http:
          path: main
          method: get

custom:
  warmup:
    default:
      enabled: true
      prewarm: true
```

example repo:
https://github.com/iPherian/serverless-warmup-plugin-bug

### PR DESCRIPTION
**Pull request by iPherian**
fixes #265

### CODE REVIEW

**Comment by juanjoDiaz** [comment]
Hi iPherian,

Thanks for the contribution.

Could you add a test for this new hook?
Essentially a copy of https://github.com/juanjoDiaz/serverless-plugin-warmup/blob/master/test/hook.warmupPrewarmStart.test.js#L7 but testing the new hook.

**Comment by iPherian** [comment]
@juanjoDiaz no problem

**Comment by juanjoDiaz** [comment]
thanks!

**Comment by iPherian** [comment]
@juanjoDiaz Would it be possible to release soon? This fix would be helpful to me in my projects.

**Pull request merged**
