### PR TITLE
Adjust schema to the strict mode

### PR DESCRIPTION
**Pull request by batovpasha**
Adjust schema to the strict mode that is enabled by default since AJV v7.

### CODE REVIEW

**Comment by juanjoDiaz** [comment]
Good stuff.
This are actually issues also in v2 (the properties one I already fixed it there 😅).

Can you please target master instead of v3?
Once serverless 3 is released, I'll rebase the v3 branch on top of master.

**Comment by batovpasha** [comment]
@juanjoDiaz Good, I changed the target branch.

**Comment by juanjoDiaz** [comment]
Thanks!

You've brought to this PR all the changes in the v3 branch.
Can you reset this branch to master and cherry pick the `fix: adjust schema to the strict mode` commit so just that one commit gets in?

Sorry for the confusion!

**Comment by batovpasha** [comment]
@juanjoDiaz Done.

**Pull request merged**
