### PR TITLE
Add alias option for compatibility with serverless-plugin-canary-depl…

### LINKED ISSUE #241: Lambda with alias does not get triggered as intended
Hello -
This is a nifty plugin, thanks for that!

### What
I have recently configured this plugin on my lambda which uses an alias to point at the latest deployed version.
I would like to have the warmup plugin keep the lambda function version warm which was configured behind that alias (at any given time). 

### How it's implemented?
1. My lambda is deployed and latest deployment is pointing to an alias **:live**

2. Here is the warmup settings in `serverless.yml`

```
custom:
  warmup:
    events:
      - schedule: cron(0/5 8-18 ? * MON-FRI *)
    name: lambda-warmer
    concurrency: 1
    prewarm: true
    vpc: false

functions:
  <function-name>:
    warmup:
      name: <function's logical name>:live
      enabled: true
```

### Behaviour Observed
* Warmup plugin is doing its job finely, so I can see a dedicated CloudWatch log group is updating every 5 mins with the warmup call logs. 
* However, when the real client application invokes the same lambda (with alias **:live**), AWS does not want to reuse the warmed-up container of that lambda instead it is creating a new lambda container (new CloudWatch log group) hindering the very basic premise of pre-warming it.

Please suggest.

Cheers,
ram

### PR DESCRIPTION
**Pull request by juanjoDiaz**
…oyments

Closes #241 

@ramgrandhi  can you test this and provide some feedback?

### CODE REVIEW

**Comment by ramgrandhi** [comment]
Sure, I will pick it up this weekend.

**Comment by ramgrandhi** [comment]
@juanjoDiaz - I tested it with the following setup.

- package.json:
```
  "devDependencies": {
    "serverless-plugin-warmup": "https://github.com/juanjoDiaz/serverless-plugin-warmup#add_alias_option",
    ...
  }
```

- serverless.yml:
```
custom:
  warmup:
    default:
      ....

functions:
  function-1:
    warmup:
      default:
        enabled: true
        alias: 'live'
  ...

plugins:
  ...
  - serverless-plugin-canary-deployments
  - serverless-plugin-warmup
  ...
```

This set up has caused the warmer-lambda to trigger application lambdas with an alias name now :)

Now, when I trigger the application lambda from the real consumer, it is observed that the same lambda container (that was warmed up earlier) was being reused for application calls. So, we get the benefit of warmup.

Thanks for the fix, my next question, when are you planning to merge it? :)

Cheers,
ram

**Comment by juanjoDiaz** [comment]
Thanks for the testing! 🙂 

I'll try to cut a new release today.

**Comment by juanjoDiaz** [comment]
v5.1.0 including this is already released.

**Pull request merged**
