### PR TITLE
add support to nodejs v20

### PR DESCRIPTION
**Pull request by cjnoname**

### CODE REVIEW

**Comment by cjnoname** [comment]
Please review and check. Thanks :)

**Comment by cjnoname** [comment]
Hi man, are you still maintaining this repo? @juanjoDiaz

**Comment by juanjoDiaz** [comment]
Hi @cjnoname ,

Yes. Sorry for the radio silence.
I want to bundle this change with the upgrade to mjs and SDK v3.
I have it almost there but I've been rather busy during last month.

I'll get back to it asap! 🙂

**Comment by cjnoname** [comment]
> Hi @cjnoname ,
> 
> Yes. Sorry for the radio silence. I want to bundle this change with the upgrade to mjs and SDK v3. I have it almost there but I've been rather busy during last month.
> 
> I'll get back to it asap! 🙂

All good mate :) I'll wait until everything is sorted :)

**Pull request merged**
