### PR TITLE
migrate to arm instance for reducing cost

### PR DESCRIPTION
**Pull request by chengjiaapraamcos**
Might reduce the cost for 17%-20%

### CODE REVIEW

**Comment by juanjoDiaz** [comment]
Hi @chengjiaapraamcos ,

Thanks for the contribution.
I think that it's a good idea to do this to reduce costs.
However, I also think that the architecture should be configurable like all the other settings and have proper tests.

Please let me know if you want to give it a go or you prefer me to do it.

**Comment by chengjiaapraamcos** [comment]
> Hi @chengjiaapraamcos ,
> 
> Thanks for the contribution. I think that it's a good idea to do this to reduce costs. However, I also think that the architecture should be configurable like all the other settings and have proper tests.
> 
> Please let me know if you want to give it a go or you prefer me to do it.

Hi mate,

I totally agree with you. Please take it over. 

Also, thanks for your great effort on this amazing package. Just love it. 

Cheers:)

**Comment by juanjoDiaz** [comment]
already done in main branch

**Comment by chengjiaapraamcos** [comment]
@juanjoDiaz  Many thanks mate!

**Comment by chengjiaapraamcos** [comment]
@juanjoDiaz Hi mate, just got a bit confused about the default architecture value. Is it arm or x86 by default? In my testing the default value is X86 but it saids "(defaults to arm64)" in readme which confused me. Thanks :)

**Comment by juanjoDiaz** [comment]
You are right.
The default is given by the framework itself and its x86.
It's a documentation mistake.

I'll fix it.

**Comment by chengjiaapraamcos** [comment]
Thanks mate @juanjoDiaz

**Pull request closed without merging**
